### ISSUE TITLE
Project Generator

### ISSUE THREAD

**Issue by smallfly** [smallfly/ofxOpenVR#1]
Need to make the addon play nicely with the Project Generator.

For example:
- finish the _addon_config.mk_ file.
- set the VS project's proterties (_Additional Dependencies_ and _Additionnal Library Directories_).
- copy the _openvr_api.dll_ to the bin folder.

**Comment by jvcleave** [comment]
Running into linking errors - what should the `Additional Dependencies` values be?

**Comment by smallfly** [comment]
openvr_api.lib
