### ISSUE TITLE
interface to any hmd

### ISSUE THREAD

**Issue by ghost** [smallfly/ofxOpenVR#10]

**Comment by smallfly** [comment]
Hi,

What do you exactly mean by 'data exchange'?

As mentioned on the OpenVR GitHub [repo](https://github.com/ValveSoftware/openvr), "OpenVR is an API and runtime that allows access to VR hardware from multiple vendors without requiring that applications have specific knowledge of the hardware they are targeting... "

ofxOpenVR is a wrapper of OpenVR for openFrameworks (I'm sure you know that already). openFrameworks will help you to make your application - e.g. video player, as in the 'example-360Player' project included in this addon.

Not sure I'm answering you question though.

**Comment by Pawder** [comment]
By data exchange i mean sending images from a video source to the hmd. To be more accurate, do i have to write an implementation for each device i plug in?

**Comment by smallfly** [comment]
Well have you look at the  'example-360Player' project? This exactly what this example does - it's a 360 video player.

As for "..., do i have to write an implementation for each device i plug in?" - OpenVR is there to help you with this (check the description).

Now you may still need to do simple adjustments - like camera position, etc... depending of the HDM or are targeting.

**Comment by Pawder** [comment]
thanks for the answers
