### ISSUE TITLE
OF-ify the code a bit more...

### ISSUE THREAD

**Issue by smallfly** [smallfly/ofxOpenVR#2]
For example, make it use: ofVec2f, ofMatrix4x4, ofVbo, etc.

**Comment by jvcleave** [comment]
I wonder how well this would fit in to the format of something like ofOpenVRWindow

**Comment by smallfly** [comment]
You mean to add a VR option to OF's core? If so, I don't think so, or at least it's too early (the current VR is still an infant).

**Comment by jvcleave** [comment]
Yeah, it's early - I was just thinking of a way to make it a bit more transparent/moving stuff out of ofApp.

For example - it would be cool to be able to use the [ofBoxExample](https://github.com/openframeworks/openFrameworks/blob/master/examples/3d/ofBoxExample/src/ofApp.cpp) but just be able to switch the window type
