### ISSUE TITLE
Build error current OF and openVR

### ISSUE THREAD

**Issue by fred-dev** [smallfly/ofxOpenVR#8]
No image on the Rift, only on the mirror screen. The rift reacts fine and I see the lobby in the headset, the screen shows movement and drawing.

**Comment by fred-dev** [comment]
Solved by switching to nvida graphics, had to do this from th nvidia control panel not the right click option

**Comment by smallfly** [comment]
Hi,

I'm glad to hear that you solved the error. Sorry for not replying sooner.
I'm curious to know more about the problem and what you did to solve the issue.

You were not able to build the a project?
What do you mean by "switching to nvida graphics", you are on a laptop?

Thanks!

**Comment by fred-dev** [comment]
Yes, I am on a laptop, it cannot run on the built in card, I needed to give it the discreet card. To do this you can right click on the exe, and you can run with graphics processor and choose from what you have installed. However Nvidia have thier own management tool for this that overrides th windows settings. The Nvida tool is also accessed through right clicking -> run with graphics processor-> change default graphics processor.

**Comment by smallfly** [comment]
Thanks for the info!
